gui:
  # If true, do not show a warning when amending a commit.
  skipAmendWarning: true
  skipStashWarning: false
git:
  branchPrefix: "milan/"
  parseEmoji: true
customCommands:
  - key: "G"
    command: "gh pr view -w {{.SelectedLocalBranch.Name}}"
    context: "localBranches"
    description: "Open Github PR in browser"
  - key: "G"
    command: "gh pr view -w"
    context: "commits"
    description: "Open Github PR in browser"
  - key: "<c-p>"
    command: "git prune-local"
    context: "status"
    loadingText: "Pruning..."
    description: "Prune local deleted remote branches"
